all:
  hosts:
    master1:
      ansible_host: 192.168.31.231
      ip: 192.168.31.231
      access_ip: 192.168.31.231
    worker1:
      ansible_host: 192.168.31.232
      ip: 192.168.31.232
      access_ip: 192.168.31.232
  children:
    kube_control_plane:
      hosts:
        master1:
    kube_node:
      hosts:
        worker1:
    etcd:
      hosts:
        master1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
