apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: nfs
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: "nfs-client"
  resources:
    requests:
      storage: 2Mi