kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-harbor-postgresql-0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 8Gi